anaTupleDef: AnaProd/anaTupleDef.py
histTupleDef: Analysis/histTupleDef.py
analysis_import: Analysis.hh_bbww
analysis_cache_import: Analysis.tasks:AnalysisCacheTask:AnalysisCacheMergeTask
phys_model: Run3_Model

bundles:
  core:
    period_specific: false
    patterns:
      - FLAF
      - AnaProd
      - Analysis
      - config
      - env.sh
      - soft/flaf_env
      - Corrections
      - DeepHME
      - Studies
      - include
  cmssw:
    period_specific: false
    patterns:
      - soft/CMSSW_16_0_6
  inputFileList:
    period_specific: true
    patterns:
      - data/{version}/InputFileTask/{period}
    task_requires:
      module: FLAF.AnaProd.tasks
      class: InputFileTask
  AnaTupleFileList:
    period_specific: true
    patterns:
      - data/{version}/AnaTupleFileListBuilderTask/{period}
      - data/{version}/AnaTupleFileListTask/{period}
    task_requires:
      module: FLAF.AnaProd.tasks
      class: AnaTupleFileListBuilderTask
  inference:
    period_specific: false
    patterns:
      - inference
      - StatInference

WLCGFileSystem:
  remotePathCacheHost: cms-flaf.cern.ch
  remotePathCachePort: 5000
  localPathCacheValidity: 600
  verbose: 0

runTokenServer:
  host: cms-flaf.cern.ch
  port: 5007

nEventsPerFile:
  data: 1000000
  signals: 100000
  backgrounds: 100000

corrections:
  mu:
    stages: [ HistTuple, AnalysisCache ]
    columns:
      pfRelIso04_all: Muon_pfRelIso04_all
      tightId: Muon_tightId
      tkRelIso: Muon_tkRelIso
      highPtId: Muon_highPtId
      mediumId: Muon_mediumId
      looseId: Muon_looseId
  trigger:
    stages: [ HistTuple, AnalysisCache ]
    mode: SF
  ele: { stages: [ HistTuple, AnalysisCache ] }
  fatjet:
    stages: [ HistTuple, AnalysisCache ] # AnaTuple
    ana: bbWW
    tagger: particleNetWithMass_HbbvsQCD
    fatJetName: fatbjet # SelectedFatJet
  muScaRe: {
    stage: AnaTuple,
    mu_pt_for_ScaReApplication: "nano",
    selection: "Muon_looseId",
  }
  eleES: { stages: [ AnaTuple, AnalysisCache ] }
  lumi: { stage: AnaTuple }
  xs: { stage: AnaTuple }
  gen: { stage: AnaTuple }
  pu:
    stages: [ AnaTuple, AnaTupleMerge ]
    enabled:
      AnaTuple: true
      AnaTupleMerge: false
  base: { stage: AnaTupleMerge }
  JEC: { stage: AnaTuple }
  JER:
    stage: AnaTuple
    apply_jet_horns_fix: true
  btag:
    normFilePattern: data/{version}/AnalysisCacheAggregationTask/{period}/{dataset_name}/BtagShape/aggregatedCache.json
    stages: [ AnaTuple, HistTuple, AnalysisCache ]
    modes:
      AnaTuple: none # just load to define WP ID branches
      AnalysisCache: shape
      HistTuple: shape_and_norm
    tagger: particleNet
    jetCollection: centralJet
  # dy_hhbbww:
  #   stages: [ AnalysisCache, HistTuple ]
  #   processes: [ DY_M_10to50, DYto2L_InclusivePlusBinned ]
  #   njets_branch: Njets # Use nCentralJets, not raw nJet
  #   pt_ll: ll_pt
  dy_hhbbtautau:
    stages: [ AnalysisCache, HistTuple ]
    processes: [ DY_M_10to50, DYto2L_InclusivePlusBinned ]
    njets_branch: Njets # Use nCentralJets, not raw nJet
    ntags_branch: nBTaggedJets
    pt_ll_gen: ll_pt_gen
extraFormat_for_triggerMatchingAndSF:
  pt: "nano"
muon_pt_for_presel: "nano"
mu_pt_for_triggerMatchingAndSF: "nano"
mu_pt_for_selection: "pt"

mu_pt_for_definitions: "ScaRe" # here options are different: corr, nano, bsConstrainedPt, roccor
muonID_WP_for_triggerSF: "Tight" # only medium or tight for trigger SF, both iso and ID
muIDWP: "Tight"
muIsoWP: "Loose"

treeName: "Events"

anaTupleSelection:
  min_n_effective_jets_SL: 3
  min_n_effective_jets_DL: 2

nPbPerFile: 2_000  # 2fb-1 per split data file

payload_producers:
  SingleLepHME:
    producers_module_name: Analysis.LegacyHMEProducer
    producer_name: HMEProducer
    channel: "SL"
    columns:
      - mass
      - valid
    dependencies:
    n_cpus: 4
    max_runtime: 30.0
    cmssw_env: True
  DoubleLepHME:
    producers_module_name: Analysis.LegacyHMEProducer
    producer_name: HMEProducer
    channel: "DL"
    columns:
      - mass
      - valid
    dependencies:
    n_cpus: 4
    max_runtime: 30.0
    cmssw_env: True
  DNN:
    producers_module_name: Analysis.DNN_Application
    producer_name: DNNProducer
    DL:
      version: "DoubleLepton_IndependentMasses_v1"
      parametric: False
    SL: null
    columns:
      - M300_Signal
      - M400_Signal
      - M500_Signal
      - M550_Signal
      - M600_Signal
      - M650_Signal
      - M700_Signal
      - M800_Signal
      - M900_Signal
      - M1000_Signal

      - M300_TT
      - M400_TT
      - M500_TT
      - M550_TT
      - M600_TT
      - M650_TT
      - M700_TT
      - M800_TT
      - M900_TT
      - M1000_TT

      - M300_DY
      - M400_DY
      - M500_DY
      - M550_DY
      - M600_DY
      - M650_DY
      - M700_DY
      - M800_DY
      - M900_DY
      - M1000_DY

      - M300_ST
      - M400_ST
      - M500_ST
      - M550_ST
      - M600_ST
      - M650_ST
      - M700_ST
      - M800_ST
      - M900_ST
      - M1000_ST
    masses:
      - 300
      - 400
      - 500
      - 550
      - 600
      - 650
      - 700
      - 800
      - 900
      - 1000
    dependencies:
    n_cpus: 4
    max_runtime: 8.0
    cmssw_env: False
    awkward_based: True
    uproot_stepsize: '50MB'
  DeepHME:
    producers_module_name: Analysis.DeepHMEProducer
    producer_name: DeepHMEProducer
    DL:
      model_name: predict_quantiles3D_DL_v12
    SL:
      model_name: predict_quantiles3D_SL_v12
    return_errors: True
    columns:
      - mass
      - mass_error
      - Hbb_px
      - Hbb_py
      - Hbb_pz
      - Hbb_E
      - HVV_px
      - HVV_py
      - HVV_pz
      - HVV_E
    n_cpus: 4
    max_runtime: 8.0
    cmssw_env: False
    awkward_based: True
    uproot_stepsize: '50MB'
    dependencies:
  BtagShape:
    producers_module_name: BtagShapeProducer
    producer_name: BtagShapeProducer
    weight_module: Analysis.hh_bbww
    save_as: json
    needs_aggregation: True
    target_groups: [ "signals", "backgrounds" ]
    is_global: True
    columns: [ ]
    bins:
      e_2: "channelId == static_cast<int>(Channel::e) && ncentralJet == 2"
      e_3: "channelId == static_cast<int>(Channel::e) && ncentralJet == 3"
      e_4: "channelId == static_cast<int>(Channel::e) && ncentralJet == 4"
      e_5: "channelId == static_cast<int>(Channel::e) && ncentralJet == 5"
      e_6: "channelId == static_cast<int>(Channel::e) && ncentralJet == 6"
      e_7: "channelId == static_cast<int>(Channel::e) && ncentralJet == 7"
      e_8: "channelId == static_cast<int>(Channel::e) && ncentralJet >= 8"
      mu_2: "channelId == static_cast<int>(Channel::mu) && ncentralJet == 2"
      mu_3: "channelId == static_cast<int>(Channel::mu) && ncentralJet == 3"
      mu_4: "channelId == static_cast<int>(Channel::mu) && ncentralJet == 4"
      mu_5: "channelId == static_cast<int>(Channel::mu) && ncentralJet == 5"
      mu_6: "channelId == static_cast<int>(Channel::mu) && ncentralJet == 6"
      mu_7: "channelId == static_cast<int>(Channel::mu) && ncentralJet == 7"
      mu_8: "channelId == static_cast<int>(Channel::mu) && ncentralJet >= 8"
      eE_2: "channelId == static_cast<int>(Channel::eE) && ncentralJet == 2"
      eE_3: "channelId == static_cast<int>(Channel::eE) && ncentralJet == 3"
      eE_4: "channelId == static_cast<int>(Channel::eE) && ncentralJet == 4"
      eE_5: "channelId == static_cast<int>(Channel::eE) && ncentralJet == 5"
      eE_6: "channelId == static_cast<int>(Channel::eE) && ncentralJet == 6"
      eE_7: "channelId == static_cast<int>(Channel::eE) && ncentralJet == 7"
      eE_8: "channelId == static_cast<int>(Channel::eE) && ncentralJet >= 8"
      eMu_2: "channelId == static_cast<int>(Channel::eMu) && ncentralJet == 2"
      eMu_3: "channelId == static_cast<int>(Channel::eMu) && ncentralJet == 3"
      eMu_4: "channelId == static_cast<int>(Channel::eMu) && ncentralJet == 4"
      eMu_5: "channelId == static_cast<int>(Channel::eMu) && ncentralJet == 5"
      eMu_6: "channelId == static_cast<int>(Channel::eMu) && ncentralJet == 6"
      eMu_7: "channelId == static_cast<int>(Channel::eMu) && ncentralJet == 7"
      eMu_8: "channelId == static_cast<int>(Channel::eMu) && ncentralJet >= 8"
      muMu_2: "channelId == static_cast<int>(Channel::muMu) && ncentralJet == 2"
      muMu_3: "channelId == static_cast<int>(Channel::muMu) && ncentralJet == 3"
      muMu_4: "channelId == static_cast<int>(Channel::muMu) && ncentralJet == 4"
      muMu_5: "channelId == static_cast<int>(Channel::muMu) && ncentralJet == 5"
      muMu_6: "channelId == static_cast<int>(Channel::muMu) && ncentralJet == 6"
      muMu_7: "channelId == static_cast<int>(Channel::muMu) && ncentralJet == 7"
      muMu_8: "channelId == static_cast<int>(Channel::muMu) && ncentralJet >= 8"
    n_cpus: 4
    max_runtime: 8.0
    cmssw_env: False
    awkward_based: True
    uproot_stepsize: '50MB'
    dependencies:

region: All
region_default: SR
custom_regions: QCDRegions
custom_categories: ""
custom_subcategories: [ ]

# Option to scale signal by some factor in HistPlotTask.py
signal_plot_scale: 100.0

# This is for Analysis Selection
channelSelection:
  - e
  - mu
  - eE
  - eMu
  - muMu

# This is for Histogram Making
channels_to_consider:
  - e
  - mu
  - eE
  - eMu
  - muMu

channelDefinition:
  e: 1  # Second lepton doesn't exist
  mu: 2
  eE: 11
  eMu: 12
  muMu: 22

categories:
  - inclusive
  - recovery
  - res2b
  - boosted
  - boosted_H
  - boosted_W
  - boosted_HW
  - baseline

QCDRegions:
  # - OS_Iso
  # - SS_Iso
  # - OS_AntiIso
  # - SS_AntiIso
  # - ZVeto_OS_Iso
  # - ZPeak_OS_Iso
  # - mbbCR_Tight
  # - mbbCR_AntiTight

  - OS_Iso
  - SR
  - TT_CR
  - DY_CR
  - W_CR
  - SR_mbb

histTuple_selectors:
  - QCDRegions
  - categories

boosted_categories: [ ]


triggers:
  e: [ singleEleWpTight ]
  mu: [ singleIsoMu ]
  eE: [ singleEleWpTight ]
  eMu: [ singleIsoMu, singleEleWpTight ]
  muMu: [ singleIsoMu ]


application_regions:
  HLT_singleEleWpTight:
    region_name: SingleE_region
    region_cut: (true)
  HLT_singleIsoMu:
    region_name: SingleMu_region
    region_cut: (true)


var_only_boosted: [ ]

unc_to_not_consider_boosted: [ ]

uncs_to_exclude:
  Run3_2022: [ ]
  Run3_2022EE: [ ]
  Run3_2023: [ ]
  Run3_2023BPix: [ ]

storeExtraJets: False
scales:
  - Up
  - Down
deepTauVersion: 2p1
met_type: "PuppiMET"

histTuple_flavor: default
histTuple_flavors:
  DNN_training:
    fullResolution_variables:
      - lep1_pt
      - lep1_eta
      - lep1_phi
      - lep1_mass

      - lep2_pt
      - lep2_eta
      - lep2_phi
      - lep2_mass

      - bjet1_pt
      - bjet1_phi
      - bjet1_eta
      - bjet1_mass
      - bjet1_btagPNetB

      - bjet2_pt
      - bjet2_phi
      - bjet2_eta
      - bjet2_mass
      - bjet2_btagPNetB

      - wjet1_pt
      - wjet1_phi
      - wjet1_eta
      - wjet1_mass
      - wjet1_btagPNetB

      - wjet2_pt
      - wjet2_phi
      - wjet2_eta
      - wjet2_mass
      - wjet2_btagPNetB

      - fatbjet_pt
      - fatbjet_phi
      - fatbjet_eta
      - fatbjet_mass
      - fatbjet_particleNetWithMass_HbbvsQCD

      - fatbjet_mass_PNetCorr
      - fatbjet_msoftdrop
      - fatbjet_nConstituents
      - fatbjet_tau1
      - fatbjet_tau2
      - fatbjet_tau3
      - fatbjet_tau4

      - fatwjet_mass_PNetCorr
      - fatwjet_msoftdrop
      - fatwjet_nConstituents
      - fatwjet_tau1
      - fatwjet_tau2
      - fatwjet_tau3
      - fatwjet_tau4

      - PuppiMET_pt
      - PuppiMET_phi

      - HT
      - ll_dR
      - bb_dR
      - ll_bb_dR
      - ll_jj_dR
      - ll_dphi
      - jj_dphi
      - met_ll_dphi
      - met_bb_dphi
      - lep1_MT
      - lep2_MT
      - total_MT
      - MT
      - MT2_ll
      - MT2_bb
      - MT2_blbl
      - MT2_blbl2
      - ll_mass
      - bb_CosTheta
      - nExtraTau
      - nExtraLeps

      - bb_mass_PNetRegPtRawCorr_PNetRegPtRawCorrNeutrino

      - DeepHME_mass
      - DeepHME_mass_error

      - disc_higgs_sqr
      - disc_top_sqr
      - hadT_mass
      - lepT_mass
      - WW_ptToE
      - bb_ptToE
      - hadT_pt
      - lepT_pt
      - hadT_constituentPtFrac
      - lepT_constituentPtFrac
      - TT_mass
      - lepT_mT
      - hadT_hadW_dphi
      - hadT_hadW_deta
      - hadT_hadW_dR
      - hadW_leadbjet_dphi
      - hadW_leadbjet_deta
      - hadW_leadbjet_dR
      - hadW_mass
      - bb_dphi
      - bb_deta
      - bb_pt
      - bb_mass
      - hadW_lep_dphi
      - hadW_lep_deta
      - hadW_lep_dR
      - hadW_lepWfromT_dphi
      - hadW_lepWfromT_deta
      - hadW_lepWfromT_dR
      - hadW_lepWfromH_dphi
      - hadW_lepWfromH_deta
      - hadW_lepWfromH_dR
      - Hbb_lepWfromH_dphi
      - Hbb_lepWfromH_deta
      - Hbb_lepWfromH_dR
      - lep1_bjets_minDr
      - lep1_bjets_minDphi
      - bjet_lepWfromT_minDphi
      - bjet_lepWfromH_minDphi
      - WW_pt
      - fatbjet_2prong
      - fatbjet_3prong

      - event
      - valid

    variables:
      - DeepHME_mass
      - lep1_pt

histTuple_fullResolution_variables: [ ]

# DNN Inputs
variables:
  - lep1_pt
  - lep1_eta
  - lep1_phi
  - lep1_mass

  - name: lep1_pt_vs_eta
    vars: [ lep1_pt, lep1_eta ]
    plot_task: False

  - lep2_pt
  - lep2_eta
  - lep2_phi
  - lep2_mass

  - PuppiMET_pt
  - PuppiMET_phi

  - bjet1_pt
  - bjet1_eta
  - bjet1_phi
  - bjet1_mass
  - bjet1_btagPNetB

  - bjet2_pt
  - bjet2_eta
  - bjet2_phi
  - bjet2_mass
  - bjet2_btagPNetB

  - wjet1_pt

  - wjet2_pt

  - fatbjet_pt
  - fatbjet_eta
  - fatbjet_phi
  - fatbjet_mass
  - fatbjet_particleNetWithMass_HbbvsQCD

  - fatwjet_pt

  - bb_mass_PNetRegPtRawCorr_PNetRegPtRawCorrNeutrino
  - bb_pt
  - bb_mass

  - HT
  - ll_dR
  - bb_dR
  - ll_bb_dR
  - ll_jj_dR
  - ll_dphi
  - jj_dphi
  - met_ll_dphi
  - met_bb_dphi
  - MT
  - lep1_MT
  - lep2_MT
  - total_MT
  - MT2_ll
  - MT2_bb
  - MT2_blbl
  - MT2_blbl2
  - MT2_blbl_min
  - MT2_blbl_max
  - MT2_blbl_dR
  - ll_mass
  - bb_CosTheta

  - lep1_Muon_pfRelIso04_all
  - lep2_Muon_pfRelIso04_all
  - lep1_Electron_pfRelIso03_all
  - lep2_Electron_pfRelIso03_all
  - mT_fix

  # Variables for DY corrections
  - nJet
  - Njets
  - nBTaggedJets
  - ll_pt
  - ll_pt_gen

  # High Level
  - DeepHME_mass
  - DeepHME_mass_error

  # High Level Single Lepton
  # need to be added to hist config
  # I will comment out them for now
  # - disc_higgs_sqr
  # - disc_top_sqr
  - hadT_mass
  - lepT_mass
  - WW_ptToE
  - bb_ptToE
  - hadT_pt
  - lepT_pt
  - hadT_constituentPtFrac
  - lepT_constituentPtFrac
  # - TT_mass
  - lepT_mT
  # - hadT_hadW_dphi
  # - hadT_hadW_deta
  - hadT_hadW_dR
  # - hadW_leadbjet_dphi
  # - hadW_leadbjet_deta
  # - hadW_leadbjet_dR
  - hadW_mass
  - bb_dphi
  - bb_deta
  - bb_pt
  - bb_mass
  # - hadW_lep_dphi
  # - hadW_lep_deta
  # - hadW_lep_dR
  # - hadW_lepWfromT_dphi
  # - hadW_lepWfromT_deta
  # - hadW_lepWfromT_dR
  # - hadW_lepWfromH_dphi
  # - hadW_lepWfromH_deta
  # - hadW_lepWfromH_dR
  # - Hbb_lepWfromH_dphi
  # - Hbb_lepWfromH_deta
  - Hbb_lepWfromH_dR
  - lep1_bjets_minDr
  # - lep1_bjets_minDphi
  # - bjet_lepWfromT_minDphi
  # - bjet_lepWfromH_minDphi
  - WW_pt

  - DNN_M300_Signal
  - DNN_M400_Signal
  - DNN_M500_Signal
  - DNN_M550_Signal
  - DNN_M600_Signal
  - DNN_M650_Signal
  - DNN_M700_Signal
  - DNN_M800_Signal
  - DNN_M900_Signal
  - DNN_M1000_Signal

  - name: DNN_m300_vs_HME
    vars: [ DNN_M300_Signal, DeepHME_mass ]
  - name: DNN_m400_vs_HME
    vars: [ DNN_M400_Signal, DeepHME_mass ]
  - name: DNN_m500_vs_HME
    vars: [ DNN_M500_Signal, DeepHME_mass ]
  - name: DNN_m550_vs_HME
    vars: [ DNN_M550_Signal, DeepHME_mass ]
  - name: DNN_m600_vs_HME
    vars: [ DNN_M600_Signal, DeepHME_mass ]
  - name: DNN_m650_vs_HME
    vars: [ DNN_M650_Signal, DeepHME_mass ]
  - name: DNN_m700_vs_HME
    vars: [ DNN_M700_Signal, DeepHME_mass ]
  - name: DNN_m800_vs_HME
    vars: [ DNN_M800_Signal, DeepHME_mass ]
  - name: DNN_m900_vs_HME
    vars: [ DNN_M900_Signal, DeepHME_mass ]
  - name: DNN_m1000_vs_HME
    vars: [ DNN_M1000_Signal, DeepHME_mass ]

StatInference:
  config: config/Datacards/x_hh_bbww_DL_run3.yaml
  hist_bins: config/Datacards/CI_binning.json
  # param_values: [ 300 ]
